name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3

    - name: Lint Action
      uses: wearerequired/lint-action@v1.9.0
      with:
        - gofmt: true
        - golint: true

    - name: Test
      run: CGO_ENABLED=0 go test -v ./...
